from typing import Any
from pyttsx3.engine import Engine


class DriverProxy:
    def __init__(self, engine: Engine, driverName: str | None, debug: bool) -> None: ...
    def __del__(self) -> None: ...
    def notify(self, topic: str, **kwargs: dict[str, Any]) -> None: ...
    def setBusy(self, busy: bool) -> None: ...
    def isBusy(self) -> bool: ...
    def say(self, text: str, name: str) -> None: ...
    def stop(self) -> None: ...
    def save_to_file(self, text: str, filename: str, name: str) -> None: ...
    def getProperty(self, name: str) -> Any: ...
    def setProperty(self, name: str, value: Any) -> None: ...
    def runAndWait(self) -> None: ...
    def startLoop(self, useDriverLoop: bool) -> None: ...
    def endLoop(self, useDriverLoop: bool) -> None: ...
    def iterate(self) -> None: ...
